<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /desk/business - the case for the product, plus the exposure model.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.animateHeroStats();
D.updateSim();
D.renderFraudChart();
D.startClocks();
D.startTicker();
D.startLoop('business');
D.wireKeys();
})();
