<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /app/checking - The middle of the check: the screen you wait on while Ntiyiso scores what you sent.
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
C.startApp('checking');
  /* The work itself crosses the page boundary in sessionStorage, because a
     function cannot. No pending check means the page was opened directly. */
  var pending = C.pendingCheck();
  if(pending) C.runPendingCheck(pending);
})();
