<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /desk/live - the cockpit. Feeds media in, scores it, streams the verdict.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.wireLiveness();
var active = D.state.active;
D.$('ctxSession').textContent = active.id + ' · ' + active.intent;
D.updateStation(active);
D.setModality('voice');
D.armEscalation();
D.startClocks();
D.startTicker();
D.startLoop('live');
/* A, G and M drive the media controls, which only exist here. */
D.wireKeys(D.MEDIA_KEYS.live);
})();
