<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /app/alerts - Everything Ntiyiso has flagged for this account.
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
C.startApp('alerts');
})();
