<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /app/check - Check a message, a link or a transaction reference.
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
C.startApp('check');
})();
