<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /desk/login - the fraud desk's own sign-in screen.
 * The role picker here chooses between this console and the customer app; the
 * tabs between "Sign in" and "Create account" stay on the page because both
 * forms are short enough to sit together.
 */
(function(){
var D = window.NT.desk;
var s = D.currentSession();
if(s && s.role !== 'customer'){ location.replace('/desk/overview'); return; }
D.setRole('staff');
D.wireKeys();
})();
