<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /auth/signup - create your ntiyiso account
 * Role picker, credentials and the provider buttons, all shared. The only
 * difference between the two auth pages is which form is on the document.
 */
(function(){
var C = window.NT.cust;
C.loadState();
C.loadAlerts();
C.applyDocument();
/* Already signed in? Go straight to wherever that role belongs, so the login
   screen is never a dead end. */
if(C.session()){ C.enterApp(); return; }
C.wireAuthShell('signup');
})();
