<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /app/scam - One scam guide. The slug comes in on the query string.
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
C.startApp('scam');
})();
