<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /desk/case - load your own media and watch the same pipeline score it.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.startClocks();
D.startTicker();
D.startLoop('case');
D.wireKeys();
})();
