<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /app/history - Every check run on this device.
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
C.startApp('history');
})();
