<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /app/settings - Language, text size, theme, and what to do with your data.
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
C.startApp('settings');
})();
