<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /desk/overview - the desk's landing screen: what needs attention.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.renderHome();
D.armEscalation();
D.startClocks();
D.startTicker();
D.startLoop('home');
D.wireKeys();
})();
