#!/usr/bin/env python3
"""Compose every page of the split site from the extracted markup slices.

The markup in build/extracted/markup/ is verbatim build/monolith.html, so nothing
is retyped: each feature's index.html is the original block(s) wrapped in the
document shell, with navigation turned into real root-absolute links. The page
scripts are written here too, because each one is only a few lines.

Run after tools/extract.py:
    python tools/build_pages.py
"""

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKUP = os.path.join(ROOT, "build", "extracted", "markup")

BANNER = "<!-- Generated by tools/build_pages.py from build/monolith.html. -->\n"

LOGO = "/assets/logo.png"


# ── helpers ────────────────────────────────────────────────────────────────
def cut(name):
    with io.open(os.path.join(MARKUP, name + ".html"), encoding="utf-8") as fh:
        return fh.read().rstrip("\n")


def write(rel_path, text):
    path = os.path.join(ROOT, rel_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = BANNER + text.lstrip("\n")
    if not body.endswith("\n"):
        body += "\n"
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    print("wrote %-38s %6d bytes" % (rel_path, len(body)))


def substitute(text, old, new, count=1):
    if old not in text:
        raise SystemExit("markup target not found:\n" + old[:160])
    return text.replace(old, new, count)


def page(title, description, styles, scripts, body, html_attrs=""):
    """Wrap a body in the shared document shell. All hrefs/srcs are root-absolute."""
    links = "\n".join(
        '<link rel="stylesheet" href="%s" />' % href for href in styles)
    tags = "\n".join('<script src="%s" defer></script>' % src for src in scripts)
    return """<!DOCTYPE html>
<html lang="en-ZA" data-text="large" data-theme="system"%(attrs)s>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<meta name="description" content="%(desc)s" />
<meta name="color-scheme" content="light" />
<title>%(title)s</title>
<link rel="icon" href="%(logo)s" />
%(links)s
</head>
<body>
%(body)s
%(scripts)s
</body>
</html>
""" % {"attrs": html_attrs, "desc": description, "title": title,
       "logo": LOGO, "links": links, "body": body, "scripts": tags}


# ── navigation rewrite ─────────────────────────────────────────────────────
def use_logo(text):
    """Swap the inline SVG lockups for the real asset."""
    return re.sub(r'src="data:image/svg\+xml,[^"]*"', 'src="%s"' % LOGO, text)


def tabbar(active):
    """The four bottom tabs are four URLs. Only the one you are on is current.

    The extracted markup hard-codes aria-current on the check tab, because in
    the single-page build that was the default screen. It is stripped here and
    re-applied to whichever tab owns the page being written.
    """
    bar = use_logo(cut("m_cust_tabbar"))
    bar = bar.replace('<button data-go="%s" aria-current="page">' % "check",
                      '<button data-go="check">', 1)
    bar = re.sub(r'<button data-go="([a-z]+)">',
                 lambda m: '<a class="tabbar-link" href="/app/%s"%s>'
                 % (m.group(1),
                    ' aria-current="page"' if m.group(1) == active else ""),
                 bar)
    bar = bar.replace("</button>", "</a>")
    return bar


def appbar():
    bar = use_logo(cut("m_cust_appbar"))
    # Settings is a page, so it is a link. Sign out stays a button - it is an
    # action, not a place.
    bar = substitute(
        bar,
        '<button class="iconbtn" id="custSettings" aria-label="Settings"',
        '<a class="iconbtn" id="custSettings" href="/app/settings" aria-label="Settings"')
    bar = substitute(bar, 'stroke-linecap="round"><circle cx="12" cy="12" r="3.2"/>'
                         '<path d="M12 3v2.2M12 18.8V21M4.2 7.5l1.9 1.1M17.9 15.4l1.9 1.1'
                         'M4.2 16.5l1.9-1.1M17.9 8.6l1.9-1.1"/></svg>\n</button>',
                         'stroke-linecap="round"><circle cx="12" cy="12" r="3.2"/>'
                         '<path d="M12 3v2.2M12 18.8V21M4.2 7.5l1.9 1.1M17.9 15.4l1.9 1.1'
                         'M4.2 16.5l1.9-1.1M17.9 8.6l1.9-1.1"/></svg>\n</a>')
    return bar


RAIL_LINKS = [
    ("home", "Overview", None),
    ("live", "Live cockpit", "01"),
    ("queue", "Threat radar", "02"),
    ("business", "Business case", "03"),
    ("case", "Case study", "04"),
]
RAIL_PATHS = {"home": "/desk/overview", "live": "/desk/live", "queue": "/desk/radar",
              "business": "/desk/business", "case": "/desk/case"}


def rail(active):
    """The left rail is five links to five URLs, with one marked as current."""
    out = ['<aside class="rail">', '<nav id="navTabs" aria-label="Desk sections">']
    for view, label, num in RAIL_LINKS:
        current = ' aria-current="page"' if view == active else ""
        icon = (cut_icon(view))
        out.append('<a data-view="%s" href="%s"%s>' % (view, RAIL_PATHS[view], current))
        out.append('  <span class="n">%s</span>' % icon)
        if view == "queue":
            out.append('  <span class="t">Threat radar'
                       '<span class="rbadge" id="threatCount">2</span></span>')
        else:
            out.append('  <span class="t">%s</span>' % label)
        out.append('</a>')
    out.append('</nav>')
    tail = cut("m_desk_rail").split("</nav>", 1)[1].rstrip("\n")
    return "\n".join(out) + "\n" + tail


def cut_icon(view):
    if view != "home":
        return RAIL_LINKS[[r[0] for r in RAIL_LINKS].index(view)][2]
    return ('<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
            ' stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'
            '<path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V21h14V9.5"/></svg>')


def view(name):
    """One view per document, so it is always the one showing."""
    return use_logo(cut("m_view_" + name)).replace(
        '<section id="view-%s" class="view">' % name,
        '<section id="view-%s" class="view on">' % name, 1)


def desk_chrome(active, body):
    return "\n".join([
        cut("m_grain"),
        use_logo(cut("m_desk_header")),
        cut("m_shell_open"),
        body,
        cut("m_main_close"),
        rail(active),
        cut("m_shell_close"),
        cut("m_desk_footer"),
        cut("m_liveness_modal"),
        # Closed here, not in the slice: the source is one </div> short of
        # closing #settingsModal, and without this the toast host ends up
        # nested inside the modal, which is display:none by default.
        cut("m_settings_modal"),
        "</div><!-- /#settingsModal -->",
        cut("m_desk_toasts"),
    ])


# ── customer app pages ─────────────────────────────────────────────────────
APP_TABS = [("check", "Check a message or link"),
            ("send", "Check a payment"),
            ("library", "Scam library"),
            ("alerts", "Alerts")]

# Which tab owns which page. The four tab screens own themselves; the two
# in-the-middle check stages still read as part of "check"; the pages reached
# from the app bar or from inside a result are not on a tab at all.
TAB_OF = {"check": "check", "send": "send", "library": "library",
          "alerts": "alerts", "checking": "check", "verdict": "check"}

APP_PAGES = [
    ("check", "Check a message or link", "Paste a message, a link or a payment "
     "reference and Ntiyiso scores it before you act."),
    ("send", "Check a payment", "Score a money transfer before you release it."),
    ("library", "Scam library", "Plain-language guides to the scams Ntiyiso recognises."),
    ("alerts", "Alerts", "Everything Ntiyiso has flagged for your account."),
    ("checking", "Checking", "Ntiyiso is scoring what you sent."),
    ("verdict", "Verdict", "What Ntiyiso found, and what to do about it."),
    ("history", "Check history", "Every check you have run on this device."),
    ("settings", "Settings", "Language, text size, theme and your data."),
    ("scam", "Scam detail", "How a scam works, and what to do."),
]

CUSTOMER_STYLES = ["/shared/css/base.css", "/shared/css/customer.css"]
DESK_STYLES = ["/shared/css/base.css", "/shared/css/desk.css"]


def build_app_pages():
    toasts = cut("m_toasts")
    for name, title, description in APP_PAGES:
        body = "\n".join([
            '<div class="cust">',
            appbar(),
            '<main class="wrap" id="custScreen"></main>',
            tabbar(TAB_OF.get(name)),
            "</div>",
            "",
            toasts,
        ])
        write("app/%s/index.html" % name, page(
            title="%(t)s · Ntiyiso" % {"t": title},
            description=description,
            styles=CUSTOMER_STYLES + ["/app/%s/styles.css" % name],
            scripts=["/shared/js/customer.js", "/app/%s/script.js" % name],
            body=body,
        ))


APP_SCRIPTS = {
    "check": ("Check a message, a link or a transaction reference.",
              "C.startApp('check');"),
    "send": ("Check a money transfer before you release it.",
             "C.startApp('send');"),
    "library": ("Browse the scam library.",
                "C.startApp('library');"),
    "alerts": ("Everything Ntiyiso has flagged for this account.",
               "C.startApp('alerts');"),
    "history": ("Every check run on this device.",
                "C.startApp('history');"),
    "settings": ("Language, text size, theme, and what to do with your data.",
                 "C.startApp('settings');"),
    "scam": ("One scam guide. The slug comes in on the query string.",
             "C.startApp('scam');"),
    "checking": ("The middle of the check: the screen you wait on while Ntiyiso "
                 "scores what you sent.",
                 """C.startApp('checking');
  /* The work itself crosses the page boundary in sessionStorage, because a
     function cannot. No pending check means the page was opened directly. */
  var pending = C.pendingCheck();
  if(pending) C.runPendingCheck(pending);"""),
    "verdict": ("The result of the last check.",
                """C.startApp('verdict');
  /* Nothing checked yet and nothing left over from /app/checking. */
  if(!C.getCurrent()) C.go('/app/check');"""),
}


def build_app_scripts():
    for name, (summary, body) in APP_SCRIPTS.items():
        write("app/%s/script.js" % name, """/* /app/%s - %s
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
%s
})();
""" % (name, summary, body))


# ── customer auth pages ────────────────────────────────────────────────────
AUTH_TABS = """<div class="tabs" id="authTabs" aria-label="Sign in or create an account">
<a href="/auth/login"%(here)s>Sign in</a>
<a href="/auth/signup"%(there)s>Create account</a>
</div>"""


def auth_head():
    """The auth hero: the logo, plus the wordmark the old lockup carried.

    `m_auth_head` pointed at a 340x100 inline SVG whose art was the shield plus
    the words "mukuru NTIYISO". assets/logo.png is the shield alone, so without
    this the sign-in screen shows a bare mark with no product name on it.
    """
    head = use_logo(cut("m_auth_head"))
    head = substitute(
        head, 'alt="mukurú NTIYISO" />',
        'alt="" />\n<p class="wordmark">mukurú <b>NTIYISO</b></p>')
    return head


def auth_body(mode):
    form = cut("m_auth_signin") if mode == "signin" else cut("m_auth_signup")
    # The active mode is this page; the other one is a link.
    tabs = AUTH_TABS % {"here": ' aria-current="page"' if mode == "signin" else "",
                        "there": ' aria-current="page"' if mode == "signup" else ""}
    title = "Sign in · Ntiyiso" if mode == "signin" else "Create an account · Ntiyiso"
    label = "Sign in to Ntiyiso" if mode == "signin" else "Create your Ntiyiso account"
    return title, "\n".join([
        '<div class="auth">',
        '<div class="auth-inner">',
        auth_head(),
        cut("m_auth_step1"),
        '<div id="authStep2" class="hidden">',
        cut("m_auth_step2"),
        tabs,
        cut("m_auth_note"),
        form,
        cut("m_auth_social"),
        "</div>",
        "</div>",
        "</div>",
    ]), label


def build_auth_pages():
    for mode in ("signin", "signup"):
        name = "login" if mode == "signin" else "signup"
        title, body, label = auth_body(mode)
        write("auth/%s/index.html" % name, page(
            title=title,
            description="Sign in to Ntiyiso, or create an account. Prototype: "
                        "accounts are stored on this device only.",
            styles=["/shared/css/base.css", "/shared/css/customer.css",
                    "/shared/css/auth.css", "/auth/%s/styles.css" % name],
            scripts=["/shared/js/customer.js", "/auth/%s/script.js" % name],
            body=body,
        ))
        write("auth/%s/script.js" % name, """/* /auth/%s - %s
 * Role picker, credentials and the provider buttons, all shared. The only
 * difference between the two auth pages is which form is on the document.
 */
(function(){
var C = window.NT.cust;
C.loadState();
C.loadAlerts();
C.applyDocument();
/* Already signed in? Go straight to wherever that role belongs, so the login
   screen is never a dead end. */
if(C.session()){ C.enterApp(); return; }
C.wireAuthShell('%s');
})();
""" % (name, label.lower(), mode))


# ── fraud desk pages ───────────────────────────────────────────────────────
DESK_PAGES = [
    ("overview", "home", "Overview", "Sessions needing attention across the desk."),
    ("live", "live", "Live cockpit", "Score a voice or video call second by second."),
    ("radar", "queue", "Threat radar", "Where synthetic calls are coming from."),
    ("business", "business", "Business case", "The numbers behind Ntiyiso."),
    ("case", "case", "Case study", "Real media against deepfakes, same pipeline."),
]

DESK_SCRIPTS = {
    "overview": """/* /desk/overview - the desk's landing screen: what needs attention.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.renderHome();
D.armEscalation();
D.startClocks();
D.startTicker();
D.startLoop('home');
D.wireKeys();
})();""",
    "live": """/* /desk/live - the cockpit. Feeds media in, scores it, streams the verdict.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.wireLiveness();
var active = D.state.active;
D.$('ctxSession').textContent = active.id + ' · ' + active.intent;
D.updateStation(active);
D.setModality('voice');
D.armEscalation();
D.startClocks();
D.startTicker();
D.startLoop('live');
/* A, G and M drive the media controls, which only exist here. */
D.wireKeys(D.MEDIA_KEYS.live);
})();""",
    "radar": """/* /desk/radar - the map and the session queue. Picking a session loads it
 * into the cockpit, which is a navigation.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.updateStation(D.state.radarSel);
D.renderQueue();
D.animateRegions();
D.renderRadar();
D.startClocks();
D.startTicker();
D.startLoop('queue');
D.wireKeys();
})();""",
    "business": """/* /desk/business - the case for the product, plus the exposure model.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.animateHeroStats();
D.updateSim();
D.renderFraudChart();
D.startClocks();
D.startTicker();
D.startLoop('business');
D.wireKeys();
})();""",
    "case": """/* /desk/case - load your own media and watch the same pipeline score it.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.startClocks();
D.startTicker();
D.startLoop('case');
D.wireKeys();
})();""",
}


def build_desk_pages():
    for name, view_name, title, description in DESK_PAGES:
        write("desk/%s/index.html" % name, page(
            title="%(t)s · Ntiyiso Fraud Desk" % {"t": title},
            description=description,
            styles=DESK_STYLES + ["/desk/%s/styles.css" % name],
            scripts=["/shared/js/desk.js", "/desk/%s/script.js" % name],
            body=desk_chrome(view_name, view(view_name)),
            html_attrs=' data-risk="high"',
        ))
        write("desk/%s/script.js" % name, DESK_SCRIPTS[name])

    # The sign-in screen stands on its own: no header, rail or footer.
    write("desk/login/index.html", page(
        title="Fraud desk sign-in · Ntiyiso",
        description="Sign in to the Ntiyiso fraud desk, or jump to the customer app.",
        styles=DESK_STYLES + ["/desk/login/styles.css"],
        scripts=["/shared/js/desk.js", "/desk/login/script.js"],
        body="\n".join([use_logo(cut("m_desk_login")), "", cut("m_desk_toasts")]),
        html_attrs=' data-risk="high"',
    ))
    write("desk/login/script.js", """/* /desk/login - the fraud desk's own sign-in screen.
 * The role picker here chooses between this console and the customer app; the
 * tabs between "Sign in" and "Create account" stay on the page because both
 * forms are short enough to sit together.
 */
(function(){
var D = window.NT.desk;
var s = D.currentSession();
if(s && s.role !== 'customer'){ location.replace('/desk/overview'); return; }
D.setRole('staff');
D.wireKeys();
})();""")


# ── the root document ──────────────────────────────────────────────────────
ROOT_PAGE = """<!DOCTYPE html>
<html lang="en-ZA" data-text="large" data-theme="system">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Ntiyiso</title>
<link rel="icon" href="/assets/logo.png" />
<link rel="canonical" href="/app/check" />
<meta http-equiv="refresh" content="0; url=/app/check" />
<script>
/* Root is only a front door: send the visitor to the app, or to sign-in when
   this device has no session yet. The meta refresh above covers no-JS. */
(function(){
  try{
    var s = JSON.parse(localStorage.getItem('ntiyiso.session.v1') || 'null');
    location.replace(s && s.role === 'customer' ? '/app/check' : '/auth/login');
  }catch(e){ location.replace('/auth/login'); }
})();
</script>
</head>
<body>
<p>Ntiyiso · <a href="/app/check">customer app</a> · <a href="/auth/login">sign in</a>
· <a href="/desk/login">fraud desk</a></p>
</body>
</html>
"""


def build_root():
    write("index.html", ROOT_PAGE)


def main():
    build_auth_pages()
    build_app_pages()
    build_app_scripts()
    build_desk_pages()
    build_root()
    return 0


if __name__ == "__main__":
    sys.exit(main())