#!/usr/bin/env python3
"""Slice the extracted <style> blocks into per-feature stylesheets.

Reads build/extracted/customer.css and build/extracted/desk.css, drops the
`@scope (...) {` wrapper, rewrites `:scope` to `:root` and writes the shared
palettes plus the per-feature files.

Ranges are 1-indexed and inclusive, taken from the section maps in README.
Re-run after re-running tools/extract.py.
"""

import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "build", "extracted")

BANNER = "/* Generated by tools/split_css.py - do not edit by hand. */\n"

# App screens whose styling all lived in the shared palette, so the per-feature
# stylesheet is a note rather than rules.
NO_CSS = [
    ("check", "This screen is styled entirely by shared/css/customer.css."),
    ("send", "This screen is styled entirely by shared/css/customer.css."),
    ("library", "This screen is styled entirely by shared/css/customer.css."),
    ("alerts", "This screen is styled entirely by shared/css/customer.css."),
    ("checking", "This screen is styled entirely by shared/css/customer.css."),
    ("history", "This screen is styled entirely by shared/css/customer.css."),
    ("settings", "This screen is styled entirely by shared/css/customer.css."),
    ("scam", "This screen is styled entirely by shared/css/customer.css."),
]


def load(name):
    with io.open(os.path.join(SRC, name), encoding="utf-8") as fh:
        return fh.read().split("\n")


def grab(lines, start, end):
    """1-indexed inclusive slice, with `:scope` rewritten for :root."""
    out = []
    for line in lines[start - 1:end]:
        out.append(line.replace(":scope", ":root"))
    text = "\n".join(out).strip("\n")
    return text + "\n" if text else ""


def write(rel_path, chunks):
    path = os.path.join(ROOT, rel_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = BANNER
    for chunk in chunks:
        if chunk.strip():
            body += chunk.rstrip("\n") + "\n\n"
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body.rstrip("\n") + "\n")
    print("wrote %-42s %6d bytes" % (rel_path, len(body)))


def split_customer():
    L = load("customer.css")
    write("shared/css/customer.css", [
        "/* ── tokens ─────────────────────────────────────────────────── */",
        grab(L, 3, 52),
        "/* ── base ───────────────────────────────────────────────────── */",
        grab(L, 54, 75),
        "/* ── shared components ──────────────────────────────────────── */",
        grab(L, 77, 186),
        "/* ── customer shell ─────────────────────────────────────────── */",
        grab(L, 244, 260),
        "/* ── avatar (used on the settings screen) ───────────────────── */",
        grab(L, 267, 268),
        # The tab bar and the in-screen "data-go" buttons are <a> elements now:
        # every one of them is a real, root-absolute URL instead of a scripted
        # tab switch, so the button selectors above are mirrored here.
        """a.tabbar-link, .tabbar a{display:flex;flex-direction:column;align-items:center;
justify-content:center;gap:3px;min-height:58px;color:var(--faint);font-size:.64em;
font-weight:700;position:relative;text-decoration:none}
.tabbar a[aria-current="page"]{color:var(--brand)}
a.notice{display:flex;text-decoration:none;color:inherit}
a.row{text-decoration:none;color:inherit}
a.btn{text-decoration:none}
a.ghost,a.btn.ghost{color:var(--brand-ink)}""",
    ])
    write("shared/css/auth.css", [
        "/* ── auth layout ─────────────────────────────────────────────── */",
        # Lines 202-211 are the splash screen and 242 is the dead staff console
        # code box. The splash was a single-page affordance, and the staff
        # console was never reachable, so neither is carried across.
        grab(L, 212, 241),
        # Sign in and Create account are two URLs now, so the mode switch is a
        # pair of links. The stylesheet mirrors the original button rules.
        """.tabs a{flex:1;background:none;border:0;padding:11px;font-size:.84em;
font-weight:700;color:var(--muted);text-align:center;text-decoration:none}
.tabs a[aria-current="page"]{background:var(--brand);color:#fff}""",
        # assets/logo.png is a square mark, not the old 340x100 lockup, so the
        # hero placement is sized by height and centred.
        """.auth img.lockup{width:auto;height:58px;max-width:190px;object-fit:contain;
margin-left:auto;margin-right:auto}""",
    ])
    for name in ("login", "signup"):
        write("auth/%s/styles.css" % name, [
            "This screen is styled entirely by shared/css/auth.css."])
    write("app/verdict/styles.css", [
        "/* ── verdict + risk meter ────────────────────────────────────── */",
        grab(L, 188, 200),
    ])
    # Every feature folder carries its own stylesheet so the split is uniform,
    # even where the screen needed no rules of its own.
    for name, note in NO_CSS:
        write("app/%s/styles.css" % name, [note])


def split_desk():
    L = load("desk.css")
    shared = [
        "/* ── tokens ─────────────────────────────────────────────────── */",
        grab(L, 2, 31),
        "/* ── base ───────────────────────────────────────────────────── */",
        grab(L, 32, 47),
        "/* ── header ──────────────────────────────────────────────────── */",
        grab(L, 49, 66),
        "/* ── shell + left rail ──────────────────────────────────────── */",
        grab(L, 68, 114),
        "/* ── generic panels ─────────────────────────────────────────── */",
        grab(L, 116, 133),
        "/* ── demo / live mode toggle ────────────────────────────────── */",
        grab(L, 178, 183),
        "/* ── modal chrome + settings modal ──────────────────────────── */",
        grab(L, 184, 188),
        grab(L, 197, 205),
        "/* ── buttons ────────────────────────────────────────────────── */",
        grab(L, 246, 262),
        "/* ── footer ─────────────────────────────────────────────────── */",
        grab(L, 528, 536),
        "/* ── toasts ─────────────────────────────────────────────────── */",
        grab(L, 538, 546),
        "/* ── responsive ─────────────────────────────────────────────── */",
        grab(L, 548, 589),
        "/* ── Mukuru accent layer ────────────────────────────────────── */",
        grab(L, 591, 640),
        # The left rail is five links to five URLs, not five buttons.
        """nav#navTabs a{position:relative;display:grid;grid-template-columns:22px minmax(0,1fr);
gap:10px;align-items:start;background:none;border:0;border-left:2px solid transparent;
text-align:left;padding:10px 10px 11px 12px;color:var(--graphite);text-decoration:none;
transition:background .2s ease,color .2s ease,border-color .2s ease}
nav#navTabs a:hover{background:rgba(31,29,27,.035);color:var(--stone)}
nav#navTabs a .n{font-family:var(--mono);font-size:9.4px;letter-spacing:.08em;padding-top:3px;color:var(--graphite)}
nav#navTabs a .t{display:block;font-size:13px;font-weight:500;color:inherit;line-height:1.3}
nav#navTabs a .d{display:block;font-size:10.6px;line-height:1.45;color:var(--graphite);margin-top:3px}
nav#navTabs a.on{background:rgba(31,29,27,.05);border-left-color:var(--bone);color:var(--bone)}
nav#navTabs a.on .n{color:var(--bone)}
nav#navTabs a.on .t{font-weight:600}
nav#navTabs a.on .d{color:var(--stone)}
@media (max-width:980px){
  nav#navTabs a{border-left:0;border-bottom:2px solid transparent;padding:9px 12px;flex-shrink:0;background:var(--coal)}
  nav#navTabs a.on{border-left-color:transparent;border-bottom-color:var(--bone)}
  nav#navTabs a .d{display:none}
}""",
    ]
    write("shared/css/desk.css", shared)

    write("desk/login/styles.css", [
        "/* ── desk sign-in screen ────────────────────────────────────── */",
        grab(L, 206, 244),
    ])
    write("desk/overview/styles.css", [
        "/* ── overview ───────────────────────────────────────────────── */",
        grab(L, 135, 154),
    ])
    write("desk/live/styles.css", [
        "/* ── video evidence panel ───────────────────────────────────── */",
        grab(L, 155, 157),
        "/* ── session band ───────────────────────────────────────────── */",
        grab(L, 264, 280),
        "/* ── escalation ribbon ──────────────────────────────────────── */",
        grab(L, 282, 291),
        "/* ── liveness step-up modal ─────────────────────────────────── */",
        grab(L, 189, 196),
        "/* ── live cockpit grid ──────────────────────────────────────── */",
        grab(L, 293, 377),
    ])
    write("desk/radar/styles.css", [
        "/* ── threat radar ───────────────────────────────────────────── */",
        grab(L, 379, 410),
        "/* ── session queue table ────────────────────────────────────── */",
        grab(L, 412, 445),
    ])
    write("desk/business/styles.css", [
        "/* ── sources + pitch ────────────────────────────────────────── */",
        grab(L, 171, 177),
        "/* ── business case ──────────────────────────────────────────── */",
        grab(L, 447, 526),
    ])
    write("desk/case/styles.css", [
        "/* ── case study cards ───────────────────────────────────────── */",
        grab(L, 158, 170),
    ])


if __name__ == "__main__":
    split_customer()
    split_desk()
    sys.exit(0)