<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /app/verdict - The result of the last check.
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
C.startApp('verdict');
  /* Nothing checked yet and nothing left over from /app/checking. */
  if(!C.getCurrent()) C.go('/app/check');
})();
