<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /desk/radar - the map and the session queue. Picking a session loads it
 * into the cockpit, which is a navigation.
 */
(function(){
var D = window.NT.desk;
if(!D.startDesk()) return;
D.wireChrome();
D.wireSettings();
D.updateStation(D.state.radarSel);
D.renderQueue();
D.animateRegions();
D.renderRadar();
D.startClocks();
D.startTicker();
D.startLoop('queue');
D.wireKeys();
})();
