<!-- Generated by tools/build_pages.py from build/monolith.html. -->
/* /app/send - Check a money transfer before you release it.
 * One screen, one document. Everything shared lives in shared/js/customer.js.
 */
(function(){
var C = window.NT.cust;
C.startApp('send');
})();
